version: '3.1'

services:
  pibgama-api:
    container_name: pibgama-api
    image: node:10.13.0-alpine
    working_dir: /usr/app/current
    env_file: [ ./.env ]
    command: ./start.sh
    volumes: [ ".:/usr/app/current" ]
    ports: [ "3000:3000" ]
    networks: [ pibgama-net ]
    links: [ mongo ]

  mongo:
    container_name: mongo-db
    image: mongo
    ports: [ "27017:27017" ]
    networks: [ pibgama-net ]
    command: --logpath=/dev/null
networks:
    pibgama-net:
