apiVersion: apps/v1
kind: Deployment
metadata:
  name: pibgama-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pibgama-api
  template:
    metadata:
      labels:
        app: pibgama-api
    spec:
      containers:
        - name: api-node
          image: gcr.io/pibgama-dev/pibgama-api
          ports:
            - containerPort: 3000
          command:
            - ./start.sh
          env:
            - name: NODE_ENV
              value: production
            - name: JWT_PRIVATE_KEY
              value: JWT_PRIVATE_KEY_VALUE
            - name: JWT_PUBLIC_KEY
              value: JWT_PUBLIC_KEY_VALUE
            - name: DB_URL
              value: DB_URL_VALUE
            - name: SENDGRID_API_KEY
              value: SENDGRID_API_KEY_VALUE
            - name: EMAIL_TRANSACTIONAL
              value: contato@pibgama.com
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "150m"

