---
apiVersion: v1
kind: Pod
metadata:
  name: api-rest
  labels:
    name: api
spec:
  containers:
    - name: api-node
      image: api-node:v1
      ports:
        - containerPort: 3000
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
