kind: Service
apiVersion: v1
metadata:
  name: pibgama-api
  labels:
    run: pibgama-api
spec:
  selector:
    app: pibgama-api
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
