openapi: 3.0.0

info:
  title: API PIBGama
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 1.0.0

servers:
  - url: http://api.pibgama.com/v1
  - url: https://api.pibgama.com/v1

paths:
  /users:
    $ref: './paths/users.yaml'
  /users/{userId}:
    $ref: './paths/users.yaml#id'
  
components:
  schemas:
    User:
      $ref: './schemas/user.yaml'
   
