name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build
        # install gettext-base to use envsubst
      run: |
        sudo apt-get install -y gettext
        JWT_PRIVATE_KEY=${{ secrets.JWT_PRIVATE_KEY }} JWT_PUBLIC_KEY=${{ secrets.JWT_PUBLIC_KEY }} NODE_ENV=${{secrets.NODE_ENV}} DB_URL=${{secrets.DB_URL}} envsubst < app.yaml.template > app.yaml
      env:
        CI: true
        JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
        JWT_PUBLIC_KEY: ${{ secrets.JWT_PUBLIC_KEY }}
        NODE_ENV: ${{secrets.NODE_ENV}}
        DB_URL: ${{secrets.DB_URL}}
    - name: Deploy
      uses: actions-hub/gcloud@master
      env:
        PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
        APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
      with:
        args: app deploy app.yaml

